### ISSUE TITLE
Earley defines functions internally with common name

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/ocaml-earley-ocaml#3]
If I write 

```ocaml
let parser foo = id:''[a-zA-Z]+'' -> id
```

in a file A.ml then it seems that module A exports a function named foo. 

I think it is dangerous and this may lead to conflicts inside a project. I think that the function should be renamed with a prefix or be encapsulated inside a module.

**Comment by rlepigre** [comment]
Well I'm not so sure. This actually corresponds to a usual value definition, this is just parser specification syntax. Why wouldn't you like a parser to be seen as a such?

**Comment by craff** [comment]
I agree with Rodolphe. In your example foo is a value of 
type string Eayley.grammar and you want to see it, because you may need to use it.

Earley has first class grammar !

**Comment by francoisthire** [comment]
I wrote my parser based on the examples given. But I didn't see anywhere what does the extension "let parser foo" actually do. In my mind, I thought it only declared a non terminal symbol, not a function. Maybe I missed something...

Anyway, I think now that my suggestion was bad indeed.

**Comment by rlepigre** [comment]
This is a documentation problem, we will definitely work on that before the first public release.
