### ISSUE TITLE
Error 404 (opam file)

### ISSUE THREAD

**Issue by Fourchaux** [rlepigre/ocaml-earley-ocaml#7]
Le lien de la Homepage https://rlepigre.github.io/ocaml-earley-ocaml/ renvoie un petit 404.
( cf. https://github.com/rlepigre/ocaml-earley-ocaml/blob/master/opam#L8)

**Comment by rlepigre** [comment]
Merci, je vais regarder ça dés que j'ai un moment.

**Comment by rlepigre** [comment]
C'est réparé par af8a24a5c8cac7b4dc47b3cc84b49fd5305a8481, et  PR https://github.com/ocaml/opam-repository/pull/11554 devrait régler le problème sur le dépôt central d'Opam.
