### ISSUE TITLE
Configure Merlin

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/ocaml-earley-ocaml#9]
Is it possible to write a Merlin file that understands the syntax extensions offered by Earley? If yes, how?

**Comment by rlepigre** [comment]
Apparently you can add something like `FLG -pp pa_ocaml` to your `.merlin` file. However Merlin people seem to think that such syntax extensions are about to disappear, which I think will never happen.

**Comment by rlepigre** [comment]
Documentation has been updated in bd66f44c6879bfdda7e62fb977076ae36942a908.

**Comment by francoisthire** [comment]
On the following test

```
open Earley

let blank = blank_regexp ''[ \t\n\r]*''
```

adding `FLG -pp pa_ocaml` to `.merlin` does not work. Merlin still complains and prints the following error (I think the message is irrelevant though):

```
This expression has type
         blank = Input.buffer -> int -> Input.buffer * int
       but an expression was expected of type int
```

**Comment by rlepigre** [comment]
Yeah, I know it does not work perfectly, but there is no other solutions. You can still get some errors right, in parts of the code that are not parser-specific. In my editors, such errors were shown as warnings, so it might be that `Merlin` tries to do something on tokens that it cannot understand.
